spring:
  liquibase:
    drop-first: false
    contexts:
    change-log: db/changelog/Changelog.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/store
    username: postgres
    password: 2503
  jpa:
    hibernate:
      ddl-auto: validate


