create table if not exists customers
(
    id       bigint generated by default as identity
        primary key,
    name     varchar(50) not null
        unique,
    balance  bigint      not null,
    birthday date
);

create table if not exists goods
(
    id bigint generated by default as identity PRIMARY KEY,
    name varchar(50) not null unique,
    full_price int,
    description varchar,
    remains int
);

create table if not exists orders
(
    id bigint generated by default as identity PRIMARY KEY,
    good_id bigint not null,
    customer_id bigint not null,
    price_of_order int not null,
    is_discount boolean,
    discount int,
    is_credit boolean,
    order_date timestamp,
    full_paid_date timestamp,
    FOREIGN KEY(customer_id) REFERENCES customers(id),
    FOREIGN KEY(good_id) REFERENCES goods(id)
    );

